### PR TITLE
API changes

### PR DESCRIPTION
**Pull request by nackjicholson**
Reopened on a different branch name. Travis builds were failing mysteriously when trying to clone the repo.

### CODE REVIEW

**Comment by nackjicholson** [comment]
I'm not sure what's going on with the github/travis connection, but the build for this PR is passing: https://travis-ci.org/honza/anosql/builds/466033303

**Comment by nackjicholson** [comment]
I wrote these docs pretty quickly, but I think they're better than nothing. It would help if anyone could try this branch out and see how it works, but I wrote quite a few tests.

I'm comfortable merging this and calling it `1.0.0`.

**Comment by nackjicholson** [comment]
`1.0.0` from `4525fe1`

**Comment by nackjicholson** [comment]
@honza Just in case it wasn't clear, this is ready to be published to PyPi when you are able to do it.

**Comment by honza** [comment]
@nackjicholson Yes, I'm on it. Sorry for the delay.

**Comment by honza** [comment]
Tagged, signed, and published https://pypi.org/project/anosql/1.0.0/

**Pull request merged**
